### PR TITLE
configured github actions for test and linting

### PR DESCRIPTION
**Pull request by tiagokretzerwalter**

### CODE REVIEW

**Comment by brunosphair** [comment]
The problem was that we was passing que SECRET_KEY variable to the environment of Github actions, but the docker was not receiving it. So I passed the secret key as a parameter of `docker-compose run`. I used "test" as a key and it's working fine, but I don't know if this could be a problem in the future if for some reason we might need to pass the correct secret_key to github when the site is online. If that's the case, we can deal with it later.

**Review by brunosphair — APPROVED** [review]

**Comment by tiagokretzerwalter** [comment]
> The problem was that we was passing que SECRET_KEY variable to the environment of Github actions, but the docker was not receiving it. So I passed the secret key as a parameter of `docker-compose run`. I used "test" as a key and it's working fine, but I don't know if this could be a problem in the future if for some reason we might need to pass the correct secret_key to github when the site is online. If that's the case, we can deal with it later.

This way you are anyway exposing the secret to the repo. You should pass the environment variable in the docker-compose file. I already made the change

**Review by brunosphair — CHANGES_REQUESTED** [review]
The way you did it doesn't work in VSCode, because our computer don't have access to this variable ${SECRET_KEY}

**Comment by tiagokretzerwalter** [comment]
> The way you did it doesn't work in VSCode, because our computer don't have access to this variable ${SECRET_KEY}

What do you mean? It worked :)

**Comment by brunosphair** [comment]
> > The way you did it doesn't work in VSCode, because our computer don't have access to this variable ${SECRET_KEY}
> 
> What do you mean? It worked :)

Did you rebuild and run the docker in your computer?

**Comment by tiagokretzerwalter** [comment]
> 

Yep, all good.

**Comment by brunosphair** [comment]
> > 
> 
> Yep, all good.

Here raises this error:

wedding-planner-app-1  | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
wedding-planner-app-1  | [01/Sep/2022 12:14:57] "GET / HTTP/1.1" 500 59

It make senses because the VSCode don't have access to the SECRET_KEY in github secrets, then attributes a empty string to it. When decouple tries to access it, the env variable is already defined as a empty string, what is not permited by Django.

**Comment by tiagokretzerwalter** [comment]
> 



> > > 
> > 
> > 
> > Yep, all good.
> 
> Here raises this error:
> 
> wedding-planner-app-1 | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty. wedding-planner-app-1 | [01/Sep/2022 12:14:57] "GET / HTTP/1.1" 500 59
> 
> It make senses because the VSCode don't have access to the SECRET_KEY in github secrets, then attributes a empty string to it. When decouple tries to access it, the env variable is already defined as a empty string, what is not permited by Django.

VS code is just a text editor, it doesn't need to have access to anything. What we need to do is to make sure that our build will have access to the SECRET_KEY. It can detect it with environment in docker-compose. It then detects the SECRET_KEY that you have in your .env file and not from GitHub secrets (we won't store it there)

**Review by brunosphair — APPROVED** [review]

**Comment by brunosphair** [comment]
The error occurred because my `.env` file was in the wedding-project folder. When I moved it to wedding-planner the code worked properly.

**Review by gabrielpalves — APPROVED** [review]

**Review by matheusmachadomtt — APPROVED** [review]

**Pull request merged**
